"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k-i=-)atkk-mc6@3=#+1lv1&w_pl2e^l0_y=^fd&)g(^gxmvki'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Allow all hosts in development


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shipping_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# REST Framework configuration
# Disable CSRF for API endpoints in development
# DRF handles authentication/authorization separately
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Allow all methods and headers for development
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Disable CSRF for API endpoints (using token-based auth instead)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'shipping_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,  # Propagate to root logger
        },
        # Explicitly configure all shipping_app sub-loggers to ensure they log
        'shipping_app.serializers': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shipping_app.serializers.shipment_serializer': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shipping_app.services': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shipping_app.services.address_validator': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'shipping_app.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Environment variables
import os
from dotenv import load_dotenv

load_dotenv()

# Production settings - use environment variables if available
if os.getenv('DB_NAME'):
    # Production: Use PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Override SECRET_KEY, DEBUG, and ALLOWED_HOSTS from environment if set
if os.getenv('SECRET_KEY'):
    SECRET_KEY = os.getenv('SECRET_KEY')

if os.getenv('DEBUG'):
    DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

if os.getenv('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS').split(',') if host.strip()]

# Update CORS origins from environment if set
if os.getenv('CORS_ALLOWED_ORIGINS'):
    cors_origins = os.getenv('CORS_ALLOWED_ORIGINS')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Address Validation API Keys
# Priority: USPS Addresses 3.0 > USPS Web Tools (Legacy) > Google Maps > SmartyStreets > Lob > Basic validation
# At least one API key should be configured for production use
# All APIs have free tiers available

# USPS Addresses 3.0 API (NEW - OAuth-based, replaces Web Tools API)
# Web Tools API shuts down January 25, 2026 - migrate to Addresses 3.0
# Sign up at: https://developers.usps.com/
# Get credentials: Register app at https://developers.usps.com/ -> My Apps -> Add App
USPS_CLIENT_ID = os.getenv('USPS_CLIENT_ID', '')  # Consumer Key from your app
USPS_CLIENT_SECRET = os.getenv('USPS_CLIENT_SECRET', '')  # Consumer Secret from your app
USPS_USE_TEM = os.getenv('USPS_USE_TEM', 'False').lower() == 'true'  # Use Testing Environment for Mailers

# USPS Web Tools API (LEGACY - Deprecated, shutting down Jan 25, 2026)
# Only use if you haven't migrated to Addresses 3.0 yet
USPS_API_KEY = os.getenv('USPS_API_KEY', '')

# Google Maps Geocoding API (Free tier: $200/month credit)
# Get API key at: https://console.cloud.google.com/google/maps-apis
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# SmartyStreets API (Free tier: 250 lookups/month)
# Sign up at: https://www.smartystreets.com/
# Note: Requires both auth-id and auth-token
SMARTY_AUTH_ID = os.getenv('SMARTY_AUTH_ID', '')
SMARTY_AUTH_TOKEN = os.getenv('SMARTY_AUTH_TOKEN', '')

# Lob Address Verification API (Free tier: 10,000 verifications/month)
# Sign up at: https://lob.com/
# Note: API key should be base64 encoded (username:password)
LOB_API_KEY = os.getenv('LOB_API_KEY', '')
