"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k-i=-)atkk-mc6@3=#+1lv1&w_pl2e^l0_y=^fd&)g(^gxmvki'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Allow all hosts in development


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shipping_app',
]

# Base middleware - WhiteNoise will be added in production
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# REST Framework configuration
# Disable CSRF for API endpoints in development
# DRF handles authentication/authorization separately
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PRODUCTION-GRADE: PostgreSQL only (no SQLite fallback)
# All database configuration via environment variables

# Get PostgreSQL configuration from environment variables
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')

# Validate required database configuration (skip during build/collectstatic)
# During build phase, database might not be available yet
SKIP_DB_VALIDATION = os.getenv('SKIP_DB_VALIDATION', 'False').lower() == 'true'

if not SKIP_DB_VALIDATION and (not DB_NAME or not DB_USER or not DB_PASSWORD):
    raise ValueError(
        "PostgreSQL database configuration is required. "
        "Please set the following environment variables:\n"
        "  - DB_NAME: Database name\n"
        "  - DB_USER: Database user\n"
        "  - DB_PASSWORD: Database password\n"
        "  - DB_HOST: Database host (default: localhost)\n"
        "  - DB_PORT: Database port (default: 5432)\n"
        "\n"
        "Create a .env file in the backend/ directory with these variables.\n"
        "See .env.example for a template."
    )

# PostgreSQL configuration (Production-grade)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 600,  # Connection pooling for better performance
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Allow all methods and headers for development
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Disable CSRF for API endpoints (using token-based auth instead)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'shipping_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Environment variables are loaded at the top of the file
# (moved to top to ensure database config can access them)

# Address Validation API Keys
# Priority: USPS Addresses 3.0 > USPS Web Tools (Legacy) > Google Maps > SmartyStreets > Lob > Basic validation
# At least one API key should be configured for production use
# All APIs have free tiers available

# USPS Addresses 3.0 API (NEW - OAuth-based, replaces Web Tools API)
# Web Tools API shuts down January 25, 2026 - migrate to Addresses 3.0
# Sign up at: https://developers.usps.com/
# Get credentials: Register app at https://developers.usps.com/ -> My Apps -> Add App
USPS_CLIENT_ID = os.getenv('USPS_CLIENT_ID', '')  # Consumer Key from your app
USPS_CLIENT_SECRET = os.getenv('USPS_CLIENT_SECRET', '')  # Consumer Secret from your app
USPS_USE_TEM = os.getenv('USPS_USE_TEM', 'False').lower() == 'true'  # Use Testing Environment for Mailers

# USPS Web Tools API (LEGACY - Deprecated, shutting down Jan 25, 2026)
# Only use if you haven't migrated to Addresses 3.0 yet
USPS_API_KEY = os.getenv('USPS_API_KEY', '')

# Google Maps Geocoding API (Free tier: $200/month credit)
# Get API key at: https://console.cloud.google.com/google/maps-apis
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# SmartyStreets API (Free tier: 250 lookups/month)
# Sign up at: https://www.smartystreets.com/
# Note: Requires both auth-id and auth-token
SMARTY_AUTH_ID = os.getenv('SMARTY_AUTH_ID', '')
SMARTY_AUTH_TOKEN = os.getenv('SMARTY_AUTH_TOKEN', '')

# Lob Address Verification API (Free tier: 10,000 verifications/month)
# Sign up at: https://lob.com/
# Note: API key should be base64 encoded (username:password)
LOB_API_KEY = os.getenv('LOB_API_KEY', '')

# Production Settings
# Detect if running in production (Render, Railway, etc.)
IS_PRODUCTION = (
    os.getenv('RENDER', '').lower() == 'true' or 
    os.getenv('RENDER_SERVICE_NAME') is not None or  # Render sets this automatically
    os.getenv('RAILWAY_ENVIRONMENT', '').lower() == 'production' or 
    os.getenv('DJANGO_ENV', '').lower() == 'production'
)

if IS_PRODUCTION:
    # Security settings for production
    DEBUG = False
    SECRET_KEY = os.getenv('SECRET_KEY', SECRET_KEY)  # Use environment variable if set
    
    # Update ALLOWED_HOSTS from environment or use default
    allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
    if allowed_hosts_env:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
    else:
        ALLOWED_HOSTS = ['*']  # Will be set by deployment platform
    
    # CORS settings for production
    cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
    if cors_origins:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]
    else:
        CORS_ALLOWED_ORIGINS = [
            "https://frontend-phi-three-66.vercel.app",
            "https://frontend-o94p5b365-dhineshmuthukaruppan-9911s-projects.vercel.app",
            "https://bulk-shipping-frontend.vercel.app",
            "https://bulk-shipping-frontend.netlify.app",
        ]
    
    # CSRF trusted origins
    csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',')]
    else:
        CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
    
    # Static files (WhiteNoise)
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Add WhiteNoise middleware after SecurityMiddleware
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    
    # Security headers
    SECURE_SSL_REDIRECT = False  # Let platform handle SSL
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    DEBUG = True
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    
    # Static files for development
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
