# Generated by Django 6.0.1 on 2026-01-11 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Saved Addresses',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_oz', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Saved Packages',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_first_name', models.CharField(blank=True, max_length=100)),
                ('from_last_name', models.CharField(blank=True, max_length=100)),
                ('from_address', models.TextField(blank=True)),
                ('from_address2', models.CharField(blank=True, max_length=200)),
                ('from_city', models.CharField(blank=True, max_length=100)),
                ('from_state', models.CharField(blank=True, max_length=2)),
                ('from_zip', models.CharField(blank=True, max_length=10)),
                ('from_phone', models.CharField(blank=True, max_length=20)),
                ('to_first_name', models.CharField(max_length=100)),
                ('to_last_name', models.CharField(blank=True, max_length=100)),
                ('to_address', models.TextField()),
                ('to_address2', models.CharField(blank=True, max_length=200)),
                ('to_city', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=2)),
                ('to_zip', models.CharField(max_length=10)),
                ('to_phone', models.CharField(blank=True, max_length=20)),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_oz', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('length', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('item_sku', models.CharField(blank=True, max_length=100)),
                ('phone_num1', models.CharField(blank=True, max_length=20)),
                ('phone_num2', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('error', 'Error'), ('ready', 'Ready to Ship'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('shipping_service', models.CharField(blank=True, default='Ground Shipping', max_length=50)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_validated', models.BooleanField(default=False)),
                ('address_validation_api_used', models.CharField(blank=True, max_length=50)),
                ('address_corrections', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_size', models.CharField(choices=[('letter', 'Letter/A4'), ('4x6', '4x6 inch')], default='letter', max_length=20)),
                ('label_data', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='shipping_app.shipment')),
            ],
        ),
    ]
