# Generated by Django 6.0.1 on 2026-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_provider',
            field=models.CharField(blank=True, default='USPS', max_length=50),
        ),
    ]
