# Generated by Django 6.0.1 on 2026-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0002_shipment_shipping_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('needs_review', 'Needs Review'), ('invalid', 'Invalid')], default='needs_review', max_length=20),
        ),
    ]
