# Generated by Django 6.0.1 on 2026-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0003_update_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for each CSV upload batch', max_length=100),
        ),
    ]
