# Generated by Django 6.0.1 on 2026-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0004_add_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='batch_id',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('needs_review', 'Needs Review'), ('needs_review_address', 'Needs Review - Address'), ('needs_review_package', 'Needs Review - Package'), ('invalid', 'Invalid')], default='needs_review', max_length=20),
        ),
    ]
