# Generated by Django 6.0.1 on 2026-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0005_add_granular_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='process_date',
            field=models.DateField(blank=True, help_text='Date when the order was processed (for dashboard analytics)', null=True),
        ),
    ]
