# Generated by Django 6.0.1 on 2026-01-12 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0006_add_process_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='ORD', help_text="Prefix for order numbers (e.g., 'ORD', 'ORDER', 'SHIP')", max_length=20)),
                ('starting_number', models.IntegerField(default=1, help_text='Starting number for sequential IDs', validators=[django.core.validators.MinValueValidator(1)])),
                ('number_format', models.CharField(default='0000', help_text="Number format: '0000' = 4 digits (ORD-0001), '00000' = 5 digits (ORD-00001)", max_length=10)),
                ('separator', models.CharField(default='-', help_text="Separator between prefix and number (e.g., '-', '_', or empty)", max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Order Number Settings',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
