# Generated by Django 6.0.1 on 2026-01-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0007_add_volumetric_weight_and_zone_fields'),
        ('shipping_app', '0007_ordernumbersettings'),
    ]

    operations = [
    ]
