# Generated by Django 6.0.1 on 2026-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0008_merge_20260113_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='address_type',
            field=models.CharField(choices=[('from', 'Ship From'), ('to', 'Ship To')], default='from', max_length=10),
        ),
    ]
