# Generated by Django 6.0.1 on 2026-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0009_savedaddress_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='address_validation_error',
            field=models.TextField(blank=True, help_text='Error message if address validation failed'),
        ),
    ]
